apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "hmda-auth.fullname" . }}
  labels:
  annotations:
    reloader.stakater.com/search: "true"
    app: {{ template "hmda-auth.name" . }}
    chart: {{ template "hmda-auth.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "hmda-auth.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "hmda-auth.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - args:
        - apk upgrade --update-cache --available && apk add openssl &&
          openssl pkcs12 -export -in /opt/docker/certs/redis-cert/redis-crt -inkey /opt/docker/certs/redis-key/redis-key
          -out /opt/docker/server.p12 -name redis-tls -CAfile /opt/docker/certs/ca-cert/ca-crt -caname root
          -passin pass:changeit -passout pass:changeit &&
          keytool -importkeystore -deststorepass changeit -destkeypass changeit -destkeystore /opt/java/openjdk/lib/security/cacerts
          -srckeystore /opt/docker/server.p12 -srcstoretype PKCS12 -srcstorepass changeit -alias redis-tls &&
          keytool -v -list -storepass changeit -keystore /opt/java/openjdk/lib/security/cacerts 2>/dev/null | grep redis &&
          cp /opt/java/openjdk/lib/security/* /opt/docker/temporary/ 
        command:
          - /bin/sh
          - -c
          - --
        image: eclipse-temurin:20-jdk-alpine
        name: eclipse-temurin-init
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /opt/docker/temporary
            name: jksfolder
          - mountPath: /opt/docker/certs/ca-cert
            name: ca-cert
            readOnly: true
          - mountPath: /opt/docker/certs/redis-cert
            name: redis-cert
            readOnly: true
          - mountPath: /opt/docker/certs/redis-key
            name: redis-key
            readOnly: true
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/America/New_York
        - emptyDir: {}
          name: jksfolder
        - name: ca-cert
          secret:
            defaultMode: 420
            items:
              - key: ca.crt
                path: ca-crt
            secretName: redis-tls-secret
        - name: redis-cert
          secret:
            defaultMode: 420
            items:
              - key: redis.crt
                path: redis-crt
            secretName: redis-tls-secret
        - name: redis-key
          secret:
            defaultMode: 420
            items:
              - key: redis.key
                path: redis-key
            secretName: redis-tls-secret
      # serviceAccountName: {{ .Values.service.serviceAccount }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: HMDA_RUNTIME_MODE
            value: {{ .Values.hmda.runtimeMode }}
          - name: BANK_FILTER_LIST
            valueFrom:
              configMapKeyRef:
                name: bank-filter-configmap
                key: bank-filter-list
          - name: KEYCLOAK_REALM_URL
            valueFrom:
              configMapKeyRef:
                name: http-configmap
                key: auth.realmUrl
          - name: KEYCLOAK_AUTH_URL
            valueFrom:
              configMapKeyRef:
                name: http-configmap
                key: auth.url
          - name: KEYCLOAK_PUBLIC_MODULUS
            valueFrom:
              configMapKeyRef:
                name: keycloak-public-key-configmap
                key: keycloak.publicKey.modulus
          - name: KEYCLOAK_PUBLIC_EXPONENT
            valueFrom:
              configMapKeyRef:
                name: keycloak-public-key-configmap
                key: keycloak.publicKey.exponent
          - name: KEYCLOAK_ADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: hmda-auth-credentials
                key: admin-username
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hmda-auth-credentials
                key: admin-password
          - name: PG_HOST
            valueFrom:
              secretKeyRef:
                name: inst-postgres-credentials
                key: host
          - name: PG_DATABASE
            valueFrom:
              configMapKeyRef:
                name: postgresql-configmap
                key: postgres.database
          - name: PG_USER
            valueFrom:
              secretKeyRef:
                name: inst-postgres-credentials
                key: username
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: inst-postgres-credentials
                key: password
          - name: PG_SSL
            valueFrom:
              configMapKeyRef:
                name: postgresql-configmap
                key: postgres.ssl
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
