kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding-beta
subjects:
  - kind: ServiceAccount
    name: {{.Values.service.account.name}}
    namespace: beta
roleRef:
  kind: ClusterRole
  name: pod-reader-beta
  apiGroup: rbac.authorization.k8s.io
